# Используем официальный образ Node.js
FROM node:14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем файлы в контейнер
COPY . .

# Собираем приложение
RUN npm run build

# Устанавливаем сервер для обслуживания статических файлов
RUN npm install -g serve

# Указываем порт, который будет открыт в контейнере
EXPOSE 3000

# Запускаем сервер для обслуживания статических файлов
CMD ["serve", "-s", "build"]
