# Generated by Django 5.0.6 on 2024-05-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_book_booklist'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
